# Generated by Django 5.1.2 on 2024-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Feedback", "0001_initial"),
        ("xy_django_app_resource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfeedback",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_images",
                to="xy_django_app_resource.mimage",
                verbose_name="图片",
            ),
        ),
    ]
